### PR TITLE
[ricos-common] clean(theme API): "fontFamily" attr

### PR DESCRIPTION
**Pull request by Barackos**
Removal of typography's "fontFamily" property.
Breaking Change.

### CODE REVIEW

**Comment by oded-soffrin** [comment]
@Barackos still relevant or can be closed?

**Comment by Barackos** [comment]
@oded-soffrin relevant for version 9

**Comment by oded-soffrin** [comment]
we can remove typography all together from api
v9 or try and implement AST ci-rule

**Comment by Barackos** [comment]
This attribute should be changed accordingly:
https://github.com/wix/ricos/blob/master/packages/common/web/statics/styles/fonts.scss#L15

We no longer want to have a CSS value determining the fontFamily of Ricos, but a total inheritance

**Pull request closed without merging**
