### PR TITLE
[editor] fix: convert <pre/> html tag to unstyled instead of converting to code-block type

### PR DESCRIPTION
**Pull request by maimonav**
Convert `<pre/>` html tag to `unstyled` type instead of `code-block` type.

### CODE REVIEW

**Review by shaulgo — APPROVED** [review]
add changelog

**Comment by oded-soffrin** [comment]
@maimonav what's the destiny of this PR ?
I see it's ancient and approved, any reason why it hasn't been merged?

I checked the difference behavior in the exampleApp, and i'm not sure I understand the nature of this change

**Comment by maimonav** [comment]
I don't remember who asked this, @shaulgo do you remember maybe?

**Comment by shaulgo** [comment]
I'm guessing that pasting from somewhere got converted to code blocks.
I don't remember the exact instance.

**Pull request closed without merging**
