### PR TITLE
[link]: feat/custom anchor scroll

### PR DESCRIPTION
**Pull request by talevy17**

### CODE REVIEW

**Comment by maimonav** [comment]
@talevy17 Looks good, what about anchor scroll from [image plugin](https://github.com/wix/ricos/blob/master/packages/plugin-image/web/src/image-viewer.tsx#L357)?
Not sure it's needed, just a thought..

**Comment by talevy17** [comment]
> @talevy17 Looks good, what about anchor scroll from [image plugin](https://github.com/wix/ricos/blob/master/packages/plugin-image/web/src/image-viewer.tsx?rgh-link-date=2021-05-12T13%3A00%3A04Z#L357)?
> Not sure it's needed, just a thought..

I don't know, @noamtwix WDYT?

**Comment by noamtwix** [comment]
I guess you need to add this `customAnchorScroll` option to the image-viewer as well. 
This function is called when an image is linked as an anchor.

**Review by maimonav — APPROVED** [review]
Looks good, just update changelog :)

**Pull request merged**
