### PR TITLE
Poll schema

### PR DESCRIPTION
**Pull request by oded-soffrin**
Regarding https://wix.slack.com/archives/C8QHV6UM9/p1647524955771879
added a test and hacked the schema
@maimonav it looks like those fields (size, width) doesn't make much sense because they can never change anyhow?
also as discussed with @danarish4 , missing an e2e test that would've discover that schema validation

### CODE REVIEW

**Review by danarish4 — APPROVED** [review]

**Comment by maimonav** [comment]
@oded-soffrin you're correct, this was a future feature for Polls.
We can either double check that it's not being used and remove it, or keep it if we intend to implement this feature in the future.

**Comment by oded-soffrin** [comment]
> @oded-soffrin you're correct, this was a future feature for Polls. We can either double check that it's not being used and remove it, or keep it if we intend to implement this feature in the future.

How can we check?

**Comment by oded-soffrin** [comment]
@danarish4 the failing tests doesn't seem relevant, are they flaky? should we remove them ?

**Comment by maimonav** [comment]
Go over the code and check if there is a usage, and we can also contact maksym and check if he knows/if they make use of it on their side.

**Comment by danarish4** [comment]
> @danarish4 the failing tests doesn't seem relevant, are they flaky? should we remove them ?

The tests are indeed irrelevant to this PR, I have never seen them fail before (everything is green in master) 
I wouldn't remove them, since they are necessary - we can set ignore region for the image inside the table (in that case, we only care about the focus)
We will consider what to do if these tests fail repeatedly.

**Comment by oded-soffrin** [comment]
> Go over the code and check if there is a usage

Couldn't find any use case, not in product or in code (mainly looked here - https://github.com/wix/ricos/blob/master/packages/plugin-social-polls/web/src/components/PollEditor.jsx#L48)

if that's the case i'll minimize the schema only to that config (and generally will stop generating it)

**Pull request merged**
