### PR TITLE
[externals] image-client-api

### PR DESCRIPTION
**Pull request by oded-soffrin**
@justame @lxgreenFYI - first try

### CODE REVIEW

**Comment by shaulgo** [comment]
do you know why packages grew?

**Comment by shaulgo** [comment]
It will break the demos?

**Comment by oded-soffrin** [comment]
not sure what happen here

**Comment by shaulgo** [comment]
Maybe the size is because it needs to be external in the webpack config of the bundlesSizes?
Also, should be added to the demos package.json.

**Comment by oded-soffrin** [comment]
it's still in dependencies, so this change should have effect anywhere if I understand correctly. what do I miss?

**Comment by shaulgo** [comment]
My guess is that because it's not bundled in rollup. It's later bundled in webpack. And there it might be bundled twice or something like that. But because we get it from the window. It should be external in webpack as well. We shouldn't count it at all.
As for the demoes/tests. I would try to add it in the demos package.json. 
It's all a bit but it's definitely weird. I'll aim to extract it completely from ricos into wixos this Q. (Although I'm not sure if PG depend on it or not)

**Comment by oded-soffrin** [comment]
normally, adding to rollup externals prevent the code to be bundled twice, because it's can be bundled once due to webpack.
we get it from window only at wix viewer, not on other environments...

**Pull request closed without merging**
