### PR TITLE
paste image support

### PR DESCRIPTION
**Pull request by oded-soffrin**
Paste image support, using editorCommands branch

### CODE REVIEW

**Comment by oded-soffrin** [comment]
@maimonav @shaulgo that's the PR i was talking about, using editorCommands to add paste image support

**Review by shaulgo — COMMENTED** [review]
Super cool. 
I'm pretty sure I don't want to expose `block`. This is the internal data structure. Seems like blockKey should be enough. 
Once I finish going over the editor commands. I will be wiser.

**Comment by oded-soffrin** [comment]
> I'm pretty sure I don't want to expose `block`. This is the internal data structure. Seems like blockKey should be enough.

smart. changed return type to (string | void)

**Comment by maimonav** [comment]
Opened a new PR, including only required changes to add this functionality, [here](https://github.com/wix/ricos/pull/2350)

**Pull request closed without merging**
